### ISSUE TITLE
K2-ConText-18 dependency

### ISSUE THREAD

**Issue by benibela** [w3c/qt3tests#47]
```
 <dependency type="spec" value="XQ10+"/>
 <test><![CDATA[count(string(text { }))]]></test>
```

 `text { }` is a syntax error before  xq3.1

**Comment by Swapnil-2502** [comment]
Could you please elaborate it.

**Comment by Swapnil-2502** [comment]
@benibela Could you please elaborate it .

**Comment by michaelhkay** [comment]
The comment is correct, XQuery 3.0 and earlier did not allow the expression within the braces to be omitted.

**Comment by michaelhkay** [comment]
Fixed.
