### ISSUE TITLE
github move

### ISSUE THREAD

**Issue by benibela** [w3c/qt3tests#5]
I just noticed the tests are here now. They are hard to find.

When you google for "XQuery/XPath/XSLT 3.* Test Suite" it still finds https://dev.w3.org/2011/QT3-test-suite where it does not mention github

And the instructions here (e.g. Overview.html or guide/running.html ) still tell you to report bugs to the disabled w3c bugzilla

**Comment by michaelhkay** [comment]
I can't solve the problem of making the tests easier to find, but I have updated the user guide.
