### ISSUE TITLE
Incorporating qt3tests to qt4tests

### ISSUE THREAD

**Issue by ChristianGruen** [w3c/qt3tests#54]
@michaelhkay We now have two test suites that are actively maintained (this one and https://github.com/qt4cg/qt4tests/). Do we already have a standard procedure to synchronize the two repositories?

If not, I’d be glad to cherry-pick recent qt3tests commits to the QT4 repository.

**Comment by michaelhkay** [comment]
I've been doing this from time to time in a manual kind of way - reviewing file diffs in Oxygen and selectively copying changes across, rather than doing any GitHub cherry-picking.

**Comment by ChristianGruen** [comment]
I’ve just synchronized the commits from the last 6-12 months as follows (qt3tests → qt4tests):

```bash
git clone git@github.com:qt4cg/qt4tests.git
cd qt4tests/
git remote add old git@github.com:w3c/qt3tests.git
git checkout -b old
git branch -u old/master old
git cherry-pick ...the hash from the oldest qt3test commit to be migrated
git cherry-pick ...the hash from the second oldest qt3test commit
...
git cherry-pick ...the hash from the newest qt3test commit
```

One advantage is that the author of the commit is preserved this way. A few commits needed to be manually revised, though (e.g., if a test was added to the end of a file in both branches). Some other commits had already been added to qt4tests; for those cases, cherry-pick reports:

```
The previous cherry-pick is now empty, possibly due to conflict resolution.
```

…and one can do `git cherry-pick --abort`.
