### ISSUE TITLE
IsCombiningMarksforSymbols is not a unicode block anymore

### ISSUE THREAD

**Issue by faassen** [w3c/qt3tests#60]
In the XSLT tests, various test cases have been removed that use unicode blocks that have since disappeared https://github.com/w3c/xslt30-test/issues/76

This includes `IsCombiningMarksforSymbols`. But various tests in `fn/matches.re.xml`  still reference this obsolete unicode block. So I would propose we change those tests cases to use newer unicode blocks too (or remove them).

In particular:

* `re00256` (`IsCombiningMarksforSymbols`)

* `re00288` (`IsPrivateUse`)

* `re00338` (`IsCombiningMarksforSymbols`)

* `re00370` (`IsPrivateUse`)

* `re00394` (`IsGreek`)

* `re00429` (`IsCombiningMarksforSymbols`)

* `re00480` (`IsPrivateUse`)

* `re00738` (`IsGreek`)

**Comment by faassen** [comment]
Hm I see now that there's a unicode version dependency on `3.1.1` for at least some of these tests (the ones pertaining to `IsPrivateUse`, I think).

**Comment by faassen** [comment]
I do see the XSD 1.1 specification say:

> Since the older block names may appear in regular expressions
>  within XSD 1.0 schemas, implementors are encouraged to
> support the superseded block names in XSD 1.1 processors for
> compatibility, either by default or [·at user option·](https://
> www.w3.org/TR/xmlschema11-2/#dt-useroption). At the time this
> document was prepared, block names from Unicode 3.1 known > to have been superseded in this way included:

So we can argue the test suite is actually correct.

**Comment by michaelhkay** [comment]
Basically, the spec is too vague in this area for the tests to be meaningful, so it makes sense to get rid of them (or change them to use current block names as appropriate).

**Comment by michaelhkay** [comment]
These tests have been modified to use non-obsolete block names (without judging whether processors should support the obsolete names or not).
