### ISSUE TITLE
Test cases numberformat11 and numberformat12 seem incorrect

### ISSUE THREAD

**Issue by adamretter** [w3c/qt3tests#9]
I am looking at test case `numberformat11` https://github.com/w3c/qt3tests/blob/master/fn/format-number.xml#L118

```xml
<test-case name="numberformat11">
      <description>
        Creator: David Marston 
        Purpose: Test default decimal-format on pattern-only characters, positive number. </description>
      <created by="Michael Kay, Saxonica" on="2010-12-13"/>
      <!--SOURCE: numberformat/numberformat11.xml-->
      <environment>
         <decimal-format digit="!" pattern-separator="\"/>
      </environment>
      <test>format-number(26931.4,'+!!!,!!!.!!!\-!!,!!!.!!!')</test>
      <result>
         <assert-string-value>+26,931.4</assert-string-value>
      </result>
   </test-case>
```

It seems to me that this should actually raise the error `FODF1310` as the picture string is invalid. It is invalid because it fails this part of the specification:

https://www.w3.org/TR/xpath-functions-31/#syntax-of-picture-string
> A sub-picture must not contain a passive character that is preceded by an active character and that is followed by another active character.

It seems to me that, after the decimal format in the environment is redefined, the 3 characters `\-!` form a sequence of *active*, *passive*, *active* characters.

If this is the case then I believe that `numberformat12` is also incorrect and should also raise `FODF1310` for a similar reason.

Can someone confirm my understanding?

**Comment by michaelhkay** [comment]
Surely "\" is the pattern separator character and is therefore not part of any sub-picture?

**Comment by adamretter** [comment]
Doh! Yes, of course. Thanks Mike :-)
